[project]
name = "mailconveyor"
version = "0.0.1"
description = "Rerouting and sending mails with Python, trying to implement a standalone mailing list service."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
]

# https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups
[dependency-groups]
dev = [
  {include-group = "lint"},
  {include-group = "test"}
]
lint = [
  "ruff"
]
test = [
  "pytest>=9.0.2"
]

# https://docs.pytest.org/en/stable/explanation/goodpractices.html
[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = ["--import-mode=importlib"]
