# Generated by Django 6.1 on 2026-08-28 22:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailinglists', '0001_initial'),
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Email subject', max_length=500)),
                ('body', models.TextField(help_text='Email body content')),
                ('is_html', models.BooleanField(default=False, help_text='Whether the body contains HTML')),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='DRAFT', help_text='Current status of the email', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the email was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the email was last updated')),
                ('error_message', models.TextField(blank=True, help_text='Error message if email sending failed', null=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of attempts to send this email')),
                ('bounce_message', models.TextField(blank=True, help_text='Bounce message if email was returned', null=True)),
                ('log_file', models.CharField(blank=True, help_text='Path to log file for this email operation', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('mailing_lists', models.ManyToManyField(blank=True, help_text='Mailing lists to send this email to', related_name='sent_emails', to='mailinglists.mailinglist')),
                ('recipients', models.ManyToManyField(blank=True, help_text='Recipients of this email', related_name='received_emails', to='recipients.recipient')),
                ('smtp_config', models.ForeignKey(blank=True, help_text='SMTP configuration used to send this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='mailinglists.smtpconfig')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attachment file', upload_to='email_attachments/')),
                ('filename', models.CharField(help_text='Original filename of the attachment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the attachment was uploaded')),
                ('email', models.ForeignKey(help_text='Email this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(help_text='Actual email address being sent to', max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', help_text='Current status of this queue entry', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of attempts to send this email')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When this email was successfully sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this queue entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this queue entry was last updated')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority level (higher = more priority)')),
                ('email', models.ForeignKey(help_text='Email being sent', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='emails.email')),
                ('recipient', models.ForeignKey(help_text='Recipient being sent to', on_delete=django.db.models.deletion.CASCADE, related_name='email_queue_entries', to='recipients.recipient')),
            ],
            options={
                'verbose_name': 'Email Queue Entry',
                'verbose_name_plural': 'Email Queue Entries',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Severity level of the log entry', max_length=10)),
                ('operation', models.CharField(choices=[('CONNECT', 'SMTP Connection'), ('AUTH', 'SMTP Authentication'), ('SEND', 'Email Send'), ('RETRY', 'Retry'), ('BOUNCE', 'Bounce Handling'), ('QUEUE', 'Queue Operation')], help_text='Type of operation being logged', max_length=20)),
                ('message', models.TextField(help_text='Log message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the log entry was created')),
                ('email', models.ForeignKey(blank=True, help_text='Email this log entry relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.email')),
                ('queue_entry', models.ForeignKey(blank=True, help_text='Queue entry this log entry relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.emailqueue')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the template', max_length=200, unique=True)),
                ('subject', models.CharField(help_text='Email subject template', max_length=500)),
                ('body', models.TextField(help_text='Email body template (HTML allowed)')),
                ('is_html', models.BooleanField(default=True, help_text='Whether the body contains HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the template was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
                ('mailing_list', models.ForeignKey(blank=True, help_text='Mailing list this template belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='mailinglists.mailinglist')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status'], name='emails_emai_status_5bddd2_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['created_at'], name='emails_emai_created_72b2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sent_at'], name='emails_emai_sent_at_d16742_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['created_by'], name='emails_emai_created_05b224_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['status'], name='emails_emai_status_948ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['priority'], name='emails_emai_priorit_9d0502_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['created_at'], name='emails_emai_created_6f6996_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['email'], name='emails_emai_email_i_31dd43_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['log_level'], name='emails_emai_log_lev_fe8b72_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['operation'], name='emails_emai_operati_6d21db_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='emails_emai_created_8a5fea_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email'], name='emails_emai_email_i_092fef_idx'),
        ),
    ]
