# Generated by Django 6.1 on 2026-08-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_using_template', to='emails.emailtemplate'),
        ),
    ]
