# Generated by Django 6.1 on 2026-08-28 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the mailing list', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the mailing list purpose', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the mailing list was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the mailing list was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this mailing list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mailinglists', to=settings.AUTH_USER_MODEL)),
                ('users_with_access', models.ManyToManyField(blank=True, help_text='Users who have access to this mailing list', related_name='accessible_mailinglists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mailing List',
                'verbose_name_plural': 'Mailing Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SMTP server hostname or IP address', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP server port')),
                ('username', models.CharField(blank=True, help_text='SMTP authentication username', max_length=255, null=True)),
                ('_password', models.TextField(blank=True, db_column='password', help_text='Encrypted SMTP password', null=True)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS for secure connection')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL for secure connection')),
                ('default_from_email', models.EmailField(blank=True, help_text="Default 'From' email address for emails sent from this list", max_length=254, null=True)),
                ('mailing_list', models.OneToOneField(help_text='The mailing list this SMTP config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='mailinglists.mailinglist')),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
            },
        ),
    ]
