# Generated by Django 6.1 on 2026-08-28 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailinglists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Name of the imported file', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', help_text='Status of the import operation', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Total number of records in the file')),
                ('successful_records', models.PositiveIntegerField(default=0, help_text='Number of successfully imported records')),
                ('failed_records', models.PositiveIntegerField(default=0, help_text='Number of failed records')),
                ('error_message', models.TextField(blank=True, help_text='Error message if import failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the import was started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the import was completed', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipient Import Log',
                'verbose_name_plural': 'Recipient Import Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Recipient's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Recipient's last name", max_length=100)),
                ('email', models.EmailField(help_text="Recipient's email address", max_length=255, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the recipient was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the recipient was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipients', to=settings.AUTH_USER_MODEL)),
                ('mailing_lists', models.ManyToManyField(blank=True, help_text='Mailing lists this recipient belongs to', related_name='recipients', to='mailinglists.mailinglist')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'ordering': ['last_name', 'first_name', 'email'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'email'), name='unique_recipient_identity', violation_error_message='A recipient with this name and email already exists.')],
            },
        ),
    ]
